[package]
name = "wgpu-native"
version = "0.6.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]
edition = "2018"
description = "WebGPU native implementation on gfx-hal"
homepage = "https://github.com/gfx-rs/wgpu-native"
repository = "https://github.com/gfx-rs/wgpu-native"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = []
#metal-auto-capture = ["gfx-backend-metal/auto-capture"]
#vulkan-portability = ["wgc/gfx-backend-vulkan"]

[dependencies.wgc]
package = "wgpu-core"
git = "https://github.com/gfx-rs/wgpu"
rev = "bbeb30a2c982ac9a7bdc6f7815d46eb311678b7a"
# path = "../wgpu/wgpu-core"
version = "0.9"
features = ["raw-window-handle", "trace"]

[dependencies.wgt]
package = "wgpu-types"
git = "https://github.com/gfx-rs/wgpu"
rev = "bbeb30a2c982ac9a7bdc6f7815d46eb311678b7a"
# path = "../wgpu/wgpu-types"
version = "0.9"

[dependencies]
lazy_static = "1.1"
raw-window-handle = "0.3"
paste = "1.0"
log = "0.4"
[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
rev = "a7ac13a"
features = ["spv-in"]

# [target.'cfg(all(unix, not(target_os = "ios"), not(target_os = "macos")))'.dependencies]
# gfx-backend-vulkan = { version = "0.7", features = [] }

[build-dependencies]
bindgen = "0.58.1"

[workspace]
resolver = "2"
members = [
	"examples/helper"
]
