[package]
name = "wgpu-native"
version = "0.1.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = []
remote = ["parking_lot"]

[dependencies]
bitflags = "1.0"
lazy_static = "1.1.0"
log = "0.4"
parking_lot = { version = "0.6", optional = true }
gfx-hal = { git = "https://github.com/gfx-rs/gfx" } # required by gfx-memory
gfx-backend-empty = { git = "https://github.com/gfx-rs/gfx" }
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", optional = true }
gfx-backend-dx12 = { git = "https://github.com/gfx-rs/gfx", optional = true }
gfx-backend-metal = { git = "https://github.com/gfx-rs/gfx", optional = true }
rendy-memory = { git = "https://github.com/rustgd/rendy", rev = "ce7dd7f", features = ["gfx-hal"] }
