[package]
name = "wgpu-native"
version = "0.6.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]
edition = "2018"
description = "WebGPU native implementation on gfx-hal"
homepage = "https://github.com/gfx-rs/wgpu-native"
repository = "https://github.com/gfx-rs/wgpu-native"
keywords = ["graphics"]
license = "MPL-2.0"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = []
#metal-auto-capture = ["gfx-backend-metal/auto-capture"]
vulkan-portability = ["wgc/gfx-backend-vulkan"]

[dependencies.wgc]
package = "wgpu-core"
git = "https://github.com/gfx-rs/wgpu"
rev = "41f106d7fc8e2ca49b21aed0919fa6cc67317f7f"
# path = "../wgpu/wgpu-core"
version = "0.7"
features = ["raw-window-handle", "trace", "cross"]

[dependencies.wgt]
package = "wgpu-types"
git = "https://github.com/gfx-rs/wgpu"
rev = "41f106d7fc8e2ca49b21aed0919fa6cc67317f7f"
# path = "../wgpu/wgpu-types"
version = "0.7"

[dependencies]
lazy_static = "1.1"
raw-window-handle = "0.3"
paste = "1.0"
log = "0.4"

# [target.'cfg(all(unix, not(target_os = "ios"), not(target_os = "macos")))'.dependencies]
# gfx-backend-vulkan = { version = "0.7", features = [] }

[build-dependencies]
bindgen = "0.53.1"

[workspace]
members = [
	"examples/helper"
]