[package]
name = "helper"
version = "0.1.0"
authors = ["Clayton Walker <clayton.m.walker@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
png = "0.16"
libc = "0.2"
