target('example-framework', function()
  set_kind('static')
  set_languages('c11', 'c++17')
  add_deps('wgpu_native')
  add_files('*.c')
  add_includedirs('.', { public = true })
  add_defines('WGPU_SHARED_LIBRARY')
end)
